// Offline support for Lunchtime Lifts. Version 544aa965e497.
const CACHE = 'lunchtime-lifts-544aa965e497';
const FILES = ["./","ex/band-external-rotation-0.webp","ex/band-external-rotation-1.webp","ex/band-face-pull-0.webp","ex/band-face-pull-1.webp","ex/band-pull-apart-0.webp","ex/band-pull-apart-1.webp","ex/bent-over-row-0.webp","ex/bent-over-row-1.webp","ex/box-squat-to-chair-0.webp","ex/box-squat-to-chair-1.webp","ex/bulgarian-split-squat-0.webp","ex/bulgarian-split-squat-1.webp","ex/dead-bug-0.webp","ex/dead-bug-1.webp","ex/dead-hang-0.webp","ex/dead-hang-1.webp","ex/dumbbell-pullover-0.webp","ex/dumbbell-pullover-1.webp","ex/forearm-plank-0.webp","ex/forearm-plank-1.webp","ex/glute-bridge-0.webp","ex/glute-bridge-1.webp","ex/goblet-squat-0.webp","ex/goblet-squat-1.webp","ex/half-kneeling-one-arm-press-0.webp","ex/half-kneeling-one-arm-press-1.webp","ex/hip-thrust-0.webp","ex/hip-thrust-1.webp","ex/incline-push-up-0.webp","ex/incline-push-up-1.webp","ex/kick-up-practice-0.webp","ex/kick-up-practice-1.webp","ex/lateral-band-walk-0.webp","ex/lateral-band-walk-1.webp","ex/low-step-up-0.webp","ex/low-step-up-1.webp","ex/lying-leg-raise-0.webp","ex/lying-leg-raise-1.webp","ex/pallof-press-0.webp","ex/pallof-press-1.webp","ex/plank-walk-out-0.webp","ex/plank-walk-out-1.webp","ex/pull-up-negative-0.webp","ex/pull-up-negative-1.webp","ex/push-up-0.webp","ex/push-up-1.webp","ex/rear-delt-fly-0.webp","ex/rear-delt-fly-1.webp","ex/renegade-row-0.webp","ex/renegade-row-1.webp","ex/reverse-crunch-0.webp","ex/reverse-crunch-1.webp","ex/reverse-lunge-0.webp","ex/reverse-lunge-1.webp","ex/romanian-deadlift-0.webp","ex/romanian-deadlift-1.webp","ex/shoulder-press-0.webp","ex/shoulder-press-1.webp","ex/side-lying-external-rotation-0.webp","ex/side-lying-external-rotation-1.webp","ex/side-plank-0.webp","ex/side-plank-1.webp","ex/single-arm-row-0.webp","ex/single-arm-row-1.webp","ex/single-leg-calf-raise-0.webp","ex/single-leg-calf-raise-1.webp","ex/single-leg-hip-thrust-0.webp","ex/single-leg-hip-thrust-1.webp","ex/single-leg-rdl-0.webp","ex/single-leg-rdl-1.webp","ex/slow-mountain-climbers-0.webp","ex/slow-mountain-climbers-1.webp","ex/split-squat-0.webp","ex/split-squat-1.webp","ex/standing-woodchop-0.webp","ex/standing-woodchop-1.webp","ex/suitcase-carry-0.webp","ex/suitcase-carry-1.webp","ex/superman-0.webp","ex/superman-1.webp","ex/table-row-0.webp","ex/table-row-1.webp","ex/thruster-0.webp","ex/thruster-1.webp","ex/tuck-up-0.webp","ex/tuck-up-1.webp","ex/v-up-0.webp","ex/v-up-1.webp","ex/z-press-0.webp","ex/z-press-1.webp","fonts/OFL-bricolage.txt","fonts/OFL-figtree.txt","fonts/bricolage.woff2","fonts/figtree-400.woff2","fonts/figtree-500.woff2","fonts/figtree-600.woff2","fonts/figtree-700.woff2","icons/apple-touch-icon.png","icons/icon-192.png","icons/icon-512-maskable.png","icons/icon-512.png","index.html","manifest.webmanifest","vendor/xlsx-LICENSE","vendor/xlsx.full.min.js"];
self.addEventListener('install', e => { e.waitUntil(caches.open(CACHE).then(c => c.addAll(FILES)).then(() => self.skipWaiting())); });
self.addEventListener('activate', e => { e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', e => {
  const u = new URL(e.request.url);
  if (e.request.method !== 'GET' || u.origin !== location.origin) return; // GitHub, YouTube: always online
  if (e.request.mode === 'navigate') { e.respondWith(fetch(e.request).then(r => { const c = r.clone(); caches.open(CACHE).then(x => x.put('./', c)); return r; }).catch(() => caches.match('./'))); return; }
  e.respondWith(caches.match(e.request).then(r => r || fetch(e.request)));
});
